############################################################
# 01. Differential Expression Analysis
############################################################

# ----------------------------------------------------------
# 01.1 Clear environment
# ----------------------------------------------------------

rm(list = ls())


# ----------------------------------------------------------
# 01.2 Load required packages
# ----------------------------------------------------------

library(DESeq2)
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(stringr)
library(ggrepel)


# ----------------------------------------------------------
# 01.3 Define project directories
# ----------------------------------------------------------

# Set the project directory before running the analysis.
# Replace this path with the location of your local project.

project_dir <- "path/to/project"

setwd(project_dir)


# ----------------------------------------------------------
# 01.4 Import raw count matrix
# ----------------------------------------------------------

# Import the gene-level count matrix generated by featureCounts.
# Raw sequencing data and sample-specific files are not included
# in this public repository.

countData <- read.delim(
  "data/count_matrix.txt",
  header = TRUE,
  row.names = 1,
  check.names = FALSE,
  comment.char = "#"
)


# ----------------------------------------------------------
# 01.5 Prepare count matrix
# ----------------------------------------------------------

# Remove annotation columns generated by featureCounts
# and retain only sample-level count columns.

countData <- countData[, grepl("^Sample_", colnames(countData))]

# Convert count values to a matrix.

countData <- as.matrix(countData)

# Ensure count values are numeric.

mode(countData) <- "numeric"


# ----------------------------------------------------------
# 01.6 Define sample metadata
# ----------------------------------------------------------

# Sample identifiers are anonymized in this public repository.
# The original sample accession identifiers are intentionally
# omitted.

sample_info <- data.frame(
  row.names = colnames(countData),
  condition = c(
    rep("Control", 3),
    rep("Case", 3)
  )
)

sample_info$condition <- factor(
  sample_info$condition,
  levels = c("Control", "Case")
)


# ----------------------------------------------------------
# 01.7 Construct DESeq2 dataset
# ----------------------------------------------------------

dds <- DESeqDataSetFromMatrix(
  countData = countData,
  colData = sample_info,
  design = ~ condition
)


# ----------------------------------------------------------
# 01.8 Filter low-count genes
# ----------------------------------------------------------

# Remove genes with very low read counts across samples.
# The filtering criterion should be consistent with the
# analysis reported in the associated manuscript.

dds <- dds[
  rowSums(counts(dds) > 1) >= 3,
]


# ----------------------------------------------------------
# 01.9 Run differential expression analysis
# ----------------------------------------------------------

dds <- DESeq(dds)


# ----------------------------------------------------------
# 01.10 Extract normalized counts
# ----------------------------------------------------------

normalized_counts <- counts(
  dds,
  normalized = TRUE
)

normalized_counts <- as.data.frame(normalized_counts)

normalized_counts$Gene_ID <- rownames(normalized_counts)

normalized_counts <- normalized_counts %>%
  dplyr::select(Gene_ID, everything())


# ----------------------------------------------------------
# 01.11 Variance stabilizing transformation
# ----------------------------------------------------------

vsd <- vst(
  dds,
  blind = FALSE
)

vsd_mat <- assay(vsd)


# ----------------------------------------------------------
# 01.12 Principal Component Analysis
# ----------------------------------------------------------

# PCA is performed to assess sample-level variation and
# identify potential clustering or outlier samples.

pca_data <- plotPCA(
  vsd,
  intgroup = "condition",
  returnData = TRUE
)

percent_var <- round(
  100 * attr(pca_data, "percentVar")
)

pca_plot <- ggplot(
  pca_data,
  aes(
    x = PC1,
    y = PC2,
    color = condition
  )
) +
  geom_point(
    size = 3
  ) +
  labs(
    title = "Principal Component Analysis",
    x = paste0("PC1: ", percent_var[1], "%"),
    y = paste0("PC2: ", percent_var[2], "%")
  ) +
  theme_classic()


# ----------------------------------------------------------
# 01.13 Sample correlation and clustering
# ----------------------------------------------------------

# Calculate sample-to-sample correlations using the
# variance-stabilized expression matrix.

sample_cor <- cor(
  vsd_mat,
  method = "pearson"
)

sample_cor_df <- as.data.frame(sample_cor)


# ----------------------------------------------------------
# 01.14 Save DESeq2 objects and intermediate results
# ----------------------------------------------------------

dir.create(
  "results",
  showWarnings = FALSE,
  recursive = TRUE
)

saveRDS(
  dds,
  file = "results/dds.rds"
)

saveRDS(
  vsd,
  file = "results/vsd.rds"
)

write.csv(
  normalized_counts,
  file = "results/normalized_counts.csv",
  row.names = FALSE
)
